### ISSUE TITLE
POST request triggers 400

### ISSUE THREAD

**Issue by tschaka1904** [gxa/atlas-heatmap#3]
Hi, 

I was trying to implement the gxa viewer into the complex portal, using the this part of the documentation: 

```
import {render as expressionAtlasHeatmapRender} from 'expression-atlas-heatmap-highcharts'
...
expressionAtlasHeatmapRender({...})
```

Basically, I'm not using React but Angular and wanted to import the viewer. Here is my code: 
```
expressionAtlasHeatmapRender({
        target: 'highchartsContainer',
        experiment: this._experimentId,
        atlasUrl: 'https://www.ebi.ac.uk/gxa/',
        query: {
          gene: this.gxaParamsQueries
        },
        fail: function () {
          context._isLoaded = false;
        }
      });
```

Unfortunately, I'm getting an `HTTP 400 error`, which breaks the application. I was investigating into this a little bit and found out the using `GET` instead of `POST` made the trick: 
![gxa_post_issue](https://user-images.githubusercontent.com/5269116/31286354-cfc77c84-aab5-11e7-991f-6b7ed8fa1265.gif)

Is there something I need to configure on my side or is this a bug? 

Cheers,
Max

**Comment by tschaka1904** [comment]
Using version 3.5.14 does the trick! Thanks @alfonsomunozpomer!

**Comment by alfonsomunozpomer** [comment]
Sorry about not announcing this feature, since version 3.6 the heatmap component does a `POST` request by default. As soon as the new Gene Expression Atlas version is released (scheduled for October 16) this will be in sync with the back end. In the meantime, as you discovered, use version 3.5.
