### ISSUE TITLE
TPM instead of FPKM in reference experiments

### ISSUE THREAD

**Issue by Deniaudm** [gxa/atlas-heatmap#7]
Hi! 
I included the heatmap as a widget in our website. 
The epression level is expressed in FPKM, I'm guessing it's a default setting? 
It is also available in TPM on Expression Atlas Website. How can I change the unit on our website? I would like TPM instead of FPKM (or even both). Maybe a parameter in the expressionAtlasHeatmapHighcharts.render function? 

Is there a way to have access to all the possible parameters? (a full documentation besides the differents examples)

Thanks for your help!

**Comment by alfonsomunozpomer** [comment]
Hi @Deniaudm, that is good to hear!

What is your website and how are you including the heatmap? It’d be great to know!

From your issue I guess you’re displaying [reference experiments](https://www.ebi.ac.uk/gxa/resources/test/widget/showcase/reference-experiment/M_musculus-ASPM.html). In the [multiexperiment view](https://www.ebi.ac.uk/gxa/resources/test/widget/showcase/simple-search/H_sapiens-ENSG00000066279-JSON.html) or in [a specific experiment](https://www.ebi.ac.uk/gxa/resources/test/widget/showcase/advanced/specific_experiment.html) TPMs are returned.

As for all parameters, the supported ones are the ones featured in the [showcase gallery](https://www.ebi.ac.uk/gxa/resources/test/widget/showcase/index.html), which are pretty much [all parameters the render method accepts](https://github.com/gxa/atlas-heatmap/blob/master/src/Main.js).

If you’re displaying a reference experiment, as a temporary workaround you can explicitly request the reference experiment accession and the expression units will be TPMs. Would that work until we add a fix?

**Comment by Deniaudm** [comment]
Thanks for your reply @alfonsomunozpomer! 

My website is matrixDB. I included the heatmap as a widget:

expressionAtlasHeatmapHighcharts.render({
   target: 'heatmap', 
   experiment: 'reference',
   query: {gene: [" + list + "]}
})

(with "list" a string containing one or several " 'value': 'id' " )

I ran some test using reference experiment accession (E-MTAB-2836) and indeed, the unit is TPM.
It works but it's kinda "disapointing" if we can just display a specific smaller dataset although reference is available just to change the unit. 

Or maybe there is an accession corresponding to "reference"? 

Thanks again for your help

**Comment by alfonsomunozpomer** [comment]
Thanks for the feedback, I just saw it in e.g. http://matrixdb.univ-lyon1.fr/cgi-bin/current/newPort?type=biomolecule&value=P51587. I’ve seen that the buttons to the top right are very probably conflicting with your flavour of Bootstrap. I’ll keep it in mind for future fixes, but it looks quite good. :)

You’re right on your second assumption. A reference experiment is one of our data sets hand picked by the curation team that is representative of the species displayed. In this case the data you get by passing `experiment: 'E-MTAB-2836'` is the same as `experiment: 'reference'`.

**Comment by Deniaudm** [comment]
Yes, we get a conflict with Bootsrtap, thanks for a potential future fix :)

We have several species in our database, e.g. http://matrixdb.univ-lyon1.fr/cgi-bin/current/newPort?type=biomolecule&value=P02454
 
Can you give me (or tell me where I can find) the reference experiment accession of each species, please?

I will be able to automtically display the dataset corresponding to the species of the current page.

Thanks again for your help!

**Comment by alfonsomunozpomer** [comment]
Here is the authoritative, most up-to-date set of reference experiments:
https://github.com/gxa/atlas/blob/master/base/src/main/java/uk/ac/ebi/atlas/web/ApplicationProperties.java

Also, a bit unrelated, is that we have a mailing list intended for all developers who integrate the package (informally we call it “the widget”) in their services:
https://listserver.ebi.ac.uk/mailman/listinfo/atlas-widget

It’s the best way to keep up with new releases and (sometimes breaking) changes. We try to keep it very low traffic. Have a look, for instance, to all the messages in may unusually *high* for the list standards. :)

![image](https://user-images.githubusercontent.com/4425744/33168817-399ab0c8-d03a-11e7-976a-295778483d3f.png)

**Comment by Deniaudm** [comment]
That's perfect! 
Thanks again for your quick replies, it was very helpful.  

I'm gonna suscribe to the mailing list :)
